### Installing Pandas
Setting up the data manipulation library in the environment.

In [95]:
pip install pandas

Requirement already satisfied: pandas in e:\ML\venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in e:\ML\venv\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\ML\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\ML\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in e:\ML\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### Importing Pandas
Standard alias implementation.

In [96]:
import pandas as pd

### Introduction to Pandas Series
Creating 1D labeled arrays from lists.

In [97]:
##Series

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("series \n",series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

### Creating Series from Dictionaries
Automatic index mapping from keys.

In [98]:
##create a series from dictonary

data={'a':1,'b':2,'c':3}
ser_dict=pd.Series(data)
print(ser_dict)

a    1
b    2
c    3
dtype: int64

### Custom Indexing in Series
Explicitly defining labels for series elements.

In [99]:
data=[1,2,3]
index=['a','b','c']
pd.Series(data,index=index)

a    1
b    2
c    3
dtype: int64

### Introduction to DataFrames
Creating 2D tabular data structures from dictionaries.

In [100]:
##Dataframe
## Create a dataframe from a dictionary of list 

data={
    'Name': ['Anith','Ram','Ravi'],
    'Age' : [20,22,19],
    'City': ['Chennai','Madurai','Dindigul']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Anith   20   Chennai
1    Ram   22   Madurai
2   Ravi   19  Dindigul
<class 'pandas.DataFrame'>

### Interoperability with NumPy
Converting DataFrames to NumPy arrays for numerical processing.

In [101]:
import numpy as np
np.array(df)

array([['Anith', 20, 'Chennai'],
       ['Ram', 22, 'Madurai'],
       ['Ravi', 19, 'Dindigul']], dtype=object)

### DataFrames from List of Dictionaries
An alternative construction method common in API data handling.

In [102]:
##create a datafram from a list of dictionary 

data=[
    {'Name':'Anith','Age':20,'city':'chennai'},
    {'Name':'ram','Age':22,'city':'kovi'},
    {'Name':'Ravi','Age':18,'city':'chennai'}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age     city
0  Anith   20  chennai
1    ram   22     kovi
2   Ravi   18  chennai
<class 'pandas.DataFrame'>

### Loading External CSV Data
Using read_csv() to import datasets.

In [103]:
df1=pd.read_csv('data.csv')
df1.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

### Inspecting the DataFrame
Displaying the structure and basic content.

In [104]:
##Accessing data from dataframe 
df

    Name  Age     city
0  Anith   20  chennai
1    ram   22     kovi
2   Ravi   18  chennai

### Column Selection
Accessing a specific data column as a Series.

In [105]:
df['Name']

0    Anith
1      ram
2     Ravi
Name: Name, dtype: str

### Label-Based Indexing with loc
Retrieving rows by their index label.

In [106]:
df.loc[0]

Name      Anith
Age          20
city    chennai
Name: 0, dtype: object

### Accessing Scalars with at
Fast label-based access to a single value.

In [107]:
##Accessing a specified elements
df.at[1,'Age']

np.int64(22)

### Verification of Scalar Access

In [108]:
df.at[1,'Name']

'ram'

### Integer-Based Indexing with iat
Fast position-based access to a single value.

In [109]:
df.iat[2,2]

'chennai'

### Adding New Columns
Dynamic expansion of the DataFrame with new data.

In [110]:
df['Salary']=[15000,20000,18000]
df

    Name  Age     city  Salary
0  Anith   20  chennai   15000
1    ram   22     kovi   20000
2   Ravi   18  chennai   18000

### Removing Columns (Temporary)
Using drop() to create a view without specific columns.

In [111]:
##remove a column

df.drop('Salary',axis=1)

    Name  Age     city
0  Anith   20  chennai
1    ram   22     kovi
2   Ravi   18  chennai

### Verifying the Original DataFrame

In [112]:
df

    Name  Age     city  Salary
0  Anith   20  chennai   15000
1    ram   22     kovi   20000
2   Ravi   18  chennai   18000

### Permanent Column Removal
Using inplace=True to modify the DataFrame directly.

In [113]:
##perment remove a column

df.drop('Salary',axis=1,inplace=True)

In [114]:
df

    Name  Age     city
0  Anith   20  chennai
1    ram   22     kovi
2   Ravi   18  chennai

In [115]:
## Add age to the column

df['Age']=df['Age']+1
df

    Name  Age     city
0  Anith   21  chennai
1    ram   23     kovi
2   Ravi   19  chennai

In [116]:
df.drop(2,inplace=True)

In [117]:
df

    Name  Age     city
0  Anith   21  chennai
1    ram   23     kovi

In [119]:
df=pd.read_csv('data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [122]:
##Display the data types of each column
print("Data types: \n",df.dtypes)

print('\n')
##Describe the Dataframe
print("Statistical Summary:\n",df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object


Statistical Summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [123]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [124]:
##Group by a column and perform an aggregation
grouped=df.groupby('Product Category')['Units Sold'].mean()
print("Mean value by category:\n",grouped)

Mean value by category:
 Product Category
Beauty Products    1.150
Books              2.850
Clothing           3.625
Electronics        1.650
Home Appliances    1.475
Sports             2.200
Name: Units Sold, dtype: float64